# Browse and parse an excel file

The goal is to parse an unstructured xlsx file into a structure dataframe. There is a logic in the file but in iits current state any manipulation becomes very diffcult.

## Start by installing the necessary libraries
Always install the libraries first

In [0]:
%pip install openpyxl # Required to read xlsx files
! pip install matplotlib

Python interpreter will be restarted.
Requirement already satisfied: openpyxl in /databricks/python3/lib/python3.9/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /databricks/python3/lib/python3.9/site-packages (from openpyxl) (1.1.0)
Python interpreter will be restarted.
Requirement already satisfied: matplotlib in /databricks/python3/lib/python3.9/site-packages (3.5.1)
Requirement already satisfied: packaging>=20.0 in /databricks/python3/lib/python3.9/site-packages (from matplotlib) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in /databricks/python3/lib/python3.9/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /databricks/python3/lib/python3.9/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /databricks/python3/lib/python3.9/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: numpy>=1.17 in /databricks/python3/lib/python3.9/site-packages (from matplotlib) (1.21.5)
Requirement already satisfied: pyparsing>=2.2.1 in /databricks/python3/lib/python3.9/site-packages (from matplotlib) (3.0.4)
Requirement already satisfied: cycler>=0.10 in /databricks/python3/lib/python3.9/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /databricks/python3/lib/python3.9/site-packages (from matplotlib) (9.0.1)
Requirement already satisfied: six>=1.5 in /databricks/python3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
WARNING: You are using pip version 21.2.4; however, version 23.2.1 is available.
You should consider upgrading via the '/local_disk0/.ephemeral_nfs/envs/pythonEnv-7082d9d7-11ca-4d7d-9000-e26c82c91b47/bin/python -m pip install --upgrade pip' command.

## Define the parameters and paths that you will need

In [0]:
xlsx_dir = '/dbfs/mnt/dataplatform/acc/DataScience/sandbox/ebiz/Inbound_FC/data/input/Ecom-Ops-status_2022.xlsx'

## Load the necessary packages

In [0]:
import pandas as pd
import numpy as np
from pyspark.sql.types import *
import datetime as dt

In [0]:
xls_file = pd.read_excel(xlsx_dir, engine="openpyxl", header=None, skiprows=1, sheet_name='Operations Forecast_new')

### Check the output

Just loading the file as it is, produces a very messy output. No headers, and a lot of data that we don't need.

The data of interest is on row 32-39 (Unnamed: 1 ==  Inbound & 0.99 == ['Dry Fc', 'Dry Actuals',...]) but the dates are on row zero. Also the dataframe has the dates as columns!

Think about how to get the desired output. There are multiple ways of doing this, you could add parameters to the read_excel function (header, skip rows, ...) or you could re-shuffle the dataframe (drop columns, set index) or a combination of these methods plus any other that you may think of. Try not to hard code it too much. For example xls_file.iloc[list(range(0,1))+list(range(32,40)),] would select the rows of interest, but maybe there file could change and the rows are not exactly the same. What you know for sure is that the data of interest will be in (Unnamed: 1 ==  Inbound & 0.99 == ['Dry Fc', 'Dry Actuals',...])

This is the data that you want (though transposed and columns without the NANs)

In [0]:
xls_file.iloc[list(range(0,1))+list(range(32,40)),]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,...,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418
0,NaN,NaN,NaN,NaN,2022-01-03 00:00:00,2022-01-04 00:00:00,2022-01-05 00:00:00,2022-01-06 00:00:00,2022-01-07 00:00:00,2022-01-08 00:00:00,2022-01-09 00:00:00,NaN,2022-01-10 00:00:00,2022-01-11 00:00:00,2022-01-12 00:00:00,2022-01-13 00:00:00,2022-01-14 00:00:00,2022-01-15 00:00:00,2022-01-16 00:00:00,NaN,2022-01-17 00:00:00,2022-01-18 00:00:00,2022-01-19 00:00:00,2022-01-20 00:00:00,2022-01-21 00:00:00,2022-01-22 00:00:00,2022-01-23 00:00:00,NaN,2022-01-24 00:00:00,2022-01-25 00:00:00,2022-01-26 00:00:00,2022-01-27 00:00:00,2022-01-28 00:00:00,2022-01-29 00:00:00,2022-01-30 00:00:00,NaN,2022-01-31 00:00:00,2022-02-01 00:00:00,2022-02-02 00:00:00,2022-02-03 00:00:00,...,NaN,2022-11-28 00:00:00,2022-11-29 00:00:00,2022-11-30 00:00:00,2022-12-01 00:00:00,2022-12-02 00:00:00,2022-12-03 00:00:00,2022-12-04 00:00:00,NaN,2022-12-05 00:00:00,2022-12-06 00:00:00,2022-12-07 00:00:00,2022-12-08 00:00:00,2022-12-09 00:00:00,2022-12-10 00:00:00,2022-12-11 00:00:00,NaN,2022-12-12 00:00:00,2022-12-13 00:00:00,2022-12-14 00:00:00,2022-12-15 00:00:00,2022-12-16 00:00:00,2022-12-17 00:00:00,2022-12-18 00:00:00,NaN,2022-12-19 00:00:00,2022-12-20 00:00:00,2022-12-21 00:00:00,2022-12-22 00:00:00,2022-12-23 00:00:00,2022-12-24 00:00:00,2022-12-25 00:00:00,NaN,2022-12-26 00:00:00,2022-12-27 00:00:00,2022-12-28 00:00:00,2022-12-29 00:00:00,2022-12-30 00:00:00,2022-12-31 00:00:00,2023-01-01 00:00:00
32,NaN,Inbound,Dry Fc,369906.911780,85794.442754,65323.939111,59060.496963,54098.434315,48633.52571,56996.072927,0,377860.897606,87580.677408,66045.894881,60290.167796,54515.40693,49645.857314,59782.893277,0,393596.526903,89206.629164,66616.908335,64106.219723,61336.583149,52553.599467,59776.587064,0,395838.687870,89714.804778,66996.698679,64471.402746,61685.830913,52852.828223,60117.122532,0,402747.413860,91280.847517,68165.726998,65596.609102,62762.346199,...,510358.629320,161687,79465.92,78236.16,66038.129,57431.396,67500.02432,0,NaN,102602,68159.58,67104.48,56642.029,49260.162,57896.305535,0,NaN,127238,69614.575,68447.115,57965.376,50616.626,59171.045365,0,NaN,80000,77948.45,76588.38,69316.352,56404.259,69863.676488,0,NaN,95488,71459.27,71916.32,60346.346,52203.888,62750.131426,62750.131426
33,NaN,NaN,Dry Actuals,300694.072927,84224,49564,45890,26976,37044,56996.072927,NaN,346429.000000,71540,63644,66433,52802,43554,48456,NaN,375572.587064,81534,72886,53783,55568,52025,59776.587064,NaN,NaN,102266,80584,70974,67565,57571,61000,NaN,335491.000000,83232,80128,61760,62943,...,502624.000000,158821,70831,76542,67017,64654,64759,NaN,NaN,94568,76287,63301,54256,52050,58807,NaN,NaN,123475,68514,65979,56286,50336,39622,NaN,NaN,76525,75921,58697,62334,55510,37575,NaN,NaN,90911,63764,47680,39552,61119,46818,NaN
34,NaN,NaN,Fresh Fc,332313.282109,60969.286307,68517.000793,59891.490569,54044.997867,48691.064872,40199.441701,0,338982.516369,62238.662837,69274.246065,61138.463129,54461.558612,49704.594182,42164.991544,0,293051.834225,63394.135324,69873.170897,65008.207708,NaN,52615.776535,42160.54376,0,356346.304963,63755.267158,70271.525553,65378.528933,61624.899913,52915.359314,42400.724092,0,362565.615803,64868.165675,71497.696469,66519.567179,62700.351857,...,447214.041427,75585.111,82253.145393,70658.35008,71378.902,78786.786,68551.746955,0,NaN,64830.843,65114.580909,59472.294398,69255.102,64056.117,58798.39195,0,NaN,61429.698,61790.65578,75829.364578,57834.893,64304.836,56251.104591,0,NaN,59329.818,75542.894095,66936.562117,75872.836,69512.274,66416.081532,0,NaN,59808,67049.998422,62406.358606,76619.568,65006.548,60982.180799,60982.180799
35,NaN,NaN,Fresh,311828.441701,41000,64233,61162,55700,49534,40199.441701,0,370396.000000,71260,57337,64963,72252,49491,55093,0,370724.000000,74945,53502,75216,62482,52579,52000,0,NaN,71305,70787,70003,72377,52690,49000,NaN,320802.000000,72886,54478,71784,65786,...,391065.000000,51949,83676,72288,79141,54931,49080,NaN,NaN,49991,66540,57797,64649,55907,53175,NaN,NaN,54353,54040,70153,48375,56776,53829,NaN,NaN,64022,79284,83049,80735,56619,45235,NaN,NaN,34710,68912,57239,63748,42234,44876,NaN
36,NaN,NaN,Frozen Fc,95928.857236,49273.053738,6447.045743,14752.88495,11884.161805,7322.811052,6248.899948,0,84914.131877,37550.317302,6518.298058,11949.245422,11598.314276,10224.721563,7073.235255,0,86103.340791,41414.982635,6574.653353,18013.8648,9114.519777,5186.696705,5798.623521,0,110088.864342,64017.948174,6612.136177,15892.905977,10477.988248,7256.228627,5831.65714,0,104445.094067,46759.662037,6727.51163,20369.956489,16186.233269,...,47889.268312,11203.38,7546.891407,6533.742161,10310.724884,6499.906136,5794.623725,0,NaN,13895.94,6473.126449,5604.101354,5714.732713,5575.111377,4970.180515,0,NaN,16953.14,6402.529429,5543.00987,5652.436084,5514.343768,4915.981044,0,NaN,10408.74,7169.005126,6202.308838,6759.315238,6144.867778,5804.33398,0,NaN,11162,6642.104962,5883.382433,5951.031775,5759.074282,5269.921775,5269.921775
37,NaN,NaN,Frozen,35021.899948,5581,6110,6061,5042,5979,6248.899948,0,41516.000000,11444,7625,8343,6714,5302,2088,0,43154.623521,9042,10216,2226,10526,5346,5798.623521,0,NaN,15862,7942,6108,6322,7497,4500,NaN,36012.000000,10574,6357,9048,5523,...,44399.000000,10041,7030,6317,9961,5885,5165,NaN,NaN,10300,7784,6037,3936,4822,9305,NaN,NaN,17313,6007,5385,5435,5320,5400,NaN,NaN,9976,7090,6584,7612,6924,5612,NaN,NaN,10191,5615,5253,6037,6692,4932,NaN
38,NaN,NaN,Ultrafresh Fc,44682.948876,6538.217201,7288.014352,8645.127518,8733.406013,7745.598367,5732.585425,0,45588.454148,6674.342453,7368.560996,8825.123652,8800.720182,7906.826941,6012.879924,0,47898.300958,6798.252877,7432.267415,9383.707769,9901.899951,8369.927293,6012.245654,0,48171.142825,6836.97989,7474.639591,9437.162345,9958.280927,8417.583837,6046.496236,0,49011.876270,6956.324771,7605.064904,9601.867231,10132.068675,...,60769.211527,11221.319,10258.846607,10560.80992,10523.397,10266.234,7938.605,0,NaN,9624.747,8799.227091,9058.185602,9026.097,8805.573,6809.122,0,NaN,9519.807,8703.26122,8959.440422,8927.703,8709.594,6734.869,0,NaN,9194.387,9745.167905,10025.097883,10675.956,9705.471,7951.908,0,NaN,10500,9028.927578,9509.601394,9399.318,9096.132,7219.766,7219.766
39,NaN,NaN,Ultrafresh,46876.802626,6538.217201,9673,9394,7299,8240,5732.585425,0,53031.000000,7975,11580,9372,6957,8191,8956,0,52136.245654,8393,11081,9881,7401,9368,6012.245654,0,NaN,7699,10092,9331,7263,8345,6046.496236,NaN,38189.000000,7835,8696,8696,6011,...,50242.000000,8495,9525,9792,7832,7983,6615,NaN,NaN,5538,7995,9315,7552,6406,8100,NaN,NaN,7788,7600,8655,6974,6660,6441,NaN,NaN,9017,11339,15132,14000,9572,6169,NaN,NaN,5660,11033,10525,10458,7824,5975,NaN

In [0]:
# Read the data types of the dataframe
xls_file.dtypes

Out[5]: 0      float64
1       object
2       object
3      float64
4       object
        ...
414     object
415     object
416     object
417     object
418     object
Length: 419, dtype: object

In [0]:
#drop the unwanted columns
xls_file_new = xls_file.drop(columns=[0,1], axis=1)
xls_file_new.head()

,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418
0,NaN,NaN,2022-01-03 00:00:00,2022-01-04 00:00:00,2022-01-05 00:00:00,2022-01-06 00:00:00,2022-01-07 00:00:00,2022-01-08 00:00:00,2022-01-09 00:00:00,NaN,2022-01-10 00:00:00,2022-01-11 00:00:00,2022-01-12 00:00:00,2022-01-13 00:00:00,2022-01-14 00:00:00,2022-01-15 00:00:00,2022-01-16 00:00:00,NaN,2022-01-17 00:00:00,2022-01-18 00:00:00,2022-01-19 00:00:00,2022-01-20 00:00:00,2022-01-21 00:00:00,2022-01-22 00:00:00,2022-01-23 00:00:00,NaN,2022-01-24 00:00:00,2022-01-25 00:00:00,2022-01-26 00:00:00,2022-01-27 00:00:00,2022-01-28 00:00:00,2022-01-29 00:00:00,2022-01-30 00:00:00,NaN,2022-01-31 00:00:00,2022-02-01 00:00:00,2022-02-02 00:00:00,2022-02-03 00:00:00,2022-02-04 00:00:00,2022-02-05 00:00:00,...,NaN,2022-11-28 00:00:00,2022-11-29 00:00:00,2022-11-30 00:00:00,2022-12-01 00:00:00,2022-12-02 00:00:00,2022-12-03 00:00:00,2022-12-04 00:00:00,NaN,2022-12-05 00:00:00,2022-12-06 00:00:00,2022-12-07 00:00:00,2022-12-08 00:00:00,2022-12-09 00:00:00,2022-12-10 00:00:00,2022-12-11 00:00:00,NaN,2022-12-12 00:00:00,2022-12-13 00:00:00,2022-12-14 00:00:00,2022-12-15 00:00:00,2022-12-16 00:00:00,2022-12-17 00:00:00,2022-12-18 00:00:00,NaN,2022-12-19 00:00:00,2022-12-20 00:00:00,2022-12-21 00:00:00,2022-12-22 00:00:00,2022-12-23 00:00:00,2022-12-24 00:00:00,2022-12-25 00:00:00,NaN,2022-12-26 00:00:00,2022-12-27 00:00:00,2022-12-28 00:00:00,2022-12-29 00:00:00,2022-12-30 00:00:00,2022-12-31 00:00:00,2023-01-01 00:00:00
1,NaN,NaN,Mon,Tue,Wed,Thu,Fri,Sat,Sun,NaN,Mon,Tue,Wed,Thu,Fri,Sat,Sun,NaN,Mon,Tue,Wed,Thu,Fri,Sat,Sun,NaN,Mon,Tue,Wed,Thu,Fri,Sat,Sun,NaN,Mon,Tue,Wed,Thu,Fri,Sat,...,NaN,Mon,Tue,Wed,Thu,Fri,Sat,Sun,NaN,Mon,Tue,Wed,Thu,Fri,Sat,Sun,NaN,Mon,Tue,Wed,Thu,Fri,Sat,Sun,NaN,Mon,Tue,Wed,Thu,Fri,Sat,Sun,NaN,Mon,Tue,Wed,Thu,Fri,Sat,Sun
2,Orders Fc,4400.000000,700,750,650,500,900,900,0,4050.000000,650,550,550,500,900,900,0,4450.00000,700,600,650,600,950,950,0,4500.000000,650,600,600,600,1000,1050,0,4650.000000,750,600,600,600,1050,1050,...,6300.000000,1000,1150,1050,1000,1100,1000,0,4800.000000,750,750,725,625,1000,950,0,4825.000000,750,700,650,575,1150,1000,0,8000.0000,750,900,900,1550,1925,1975,0,9700.000,800,900,950,1400,1950,1850,1850
3,Basket Fc,NaN,43.656843,41.534592,44.275547,48.7,51.5,50.8,0,NaN,46.141493,46.282426,46.623012,49.8,53,52,0,NaN,47.174251,45.470676,47.452303,50.4,51.4,52.4,0,NaN,47.429851,44.639535,48.0,50,51,52,0,NaN,47.268702,44.711875,46.137204,47,49,49.4,...,NaN,48.785462,56.155002,50.147977,50.627842,51.520878,51.572018,0,NaN,48.496803,43.422563,44.053031,41.340876,47.857229,47.833988,0,NaN,44.908658,42.269815,41.806874,40.471524,48.71944,50.157713,0,NaN,47.77,45.47,41.73,43.1,41.7,36.61,0,NaN,41.71,42.59,41.52,40.8,40.35,35.34,35.34
4,Picking Fc,204840.741214,30254.192107,30839.434588,28491.314519,24106.5,45886.5,45262.8,NaN,198485.061305,29692.050509,25200.780835,25386.229961,24651,47223,46332,NaN,217798.39451,32691.755849,27009.581576,30535.557085,29937.6,48341.7,49282.2,NaN,219792.992676,30521.108955,26515.883721,28512.0,29700,50490,54054,NaN,219266.164702,35097.011523,26558.853862,27405.499318,27918,50935.5,51351.3,...,318394.079327,47809.753242,63286.6876,51602.26874,49615.285174,55539.506946,50540.577624,NaN,217815.382489,36008.876399,32241.253216,31619.06315,25579.667075,47378.656531,44987.866118,NaN,217702.016598,33344.678402,29292.981504,26902.72342,23038.414906,55467.082621,49656.135745,NaN,330352.8525,35469.225,40513.77,37181.43,66136.95,79469.775,71581.7025,NaN,309201.255,33034.32,37947.69,39049.56,56548.8,77895.675,64725.21,NaN

In [0]:
# Transpose the the  
xls_fileT= xls_file_new.transpose ()#.reset_index ()
#loc the fisrt row to be column names
xls_fileT.rename(columns=xls_fileT.iloc[0], inplace=True)
#Now rename the first columns from NaT to Date 
xls_fileT.head()

,NaT,NaN,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Total Picks Forecast,Total Picks Update,Inbound Fc (no PO),Pre-orders Fc,Ochtend,Middag,Nacht,Delhome+Correctie,Leverdag,Geschat,Actuals,NaN,Dry Fc,Dry Actuals,Fresh Fc,Fresh,Frozen Fc,Frozen,Ultrafresh Fc,Ultrafresh,Total Inbound Fc,Total Inbound,Distrilog Dry,Delhome Dry,Total Dry,Distrilog Rest,Total
2,NaT,NaN,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Total Picks Forecast,Total Picks Update,Inbound Fc (no PO),Pre-orders Fc,Ochtend,Middag,Nacht,Delhome+Correctie,Leverdag,Geschat,Actuals,NaN,Dry Fc,Dry Actuals,Fresh Fc,Fresh,Frozen Fc,Frozen,Ultrafresh Fc,Ultrafresh,Total Inbound Fc,Total Inbound,Distrilog Dry,Delhome Dry,Total Dry,Distrilog Rest,Total
3,NaT,NaN,4400.0,NaN,204840.741214,4323.0,NaN,200388.078,5580.0,NaN,288451.394266,5860.0,NaN,286562.331,5250.0,NaN,268811.635976,5572.0,NaN,273058.731,762103.771455,760009.14,0.0,44682.948876,NaN,NaN,NaN,NaN,796800.0,NaN,NaN,NaN,369906.91178,300694.072927,332313.282109,311828.441701,95928.857236,35021.899948,44682.948876,46876.802626,842832.0,694421.217201,NaN,NaN,NaN,NaN,NaN
4,2022-01-03,Mon,700,43.656843,30254.192107,615,44.3,26972.055,200,49.51237,9803.449231,201,53.3,10606.167,700,49.51237,34312.072307,701,53.3,36989.667,74369.713644,74567.889,0,6538.217201,35000,55000,33000,NaN,123000,35000,34000,NaN,85794.442754,84224,60969.286307,41000,49273.053738,5581,6538.217201,6538.217201,202575,137343.217201,NaN,NaN,NaN,NaN,NaN
5,2022-01-04,Tue,750,41.534592,30839.434588,676,43.5,29111.94,1100,49.145397,53519.336809,1131,47.8,53521.182,1000,49.145397,48653.942554,1040,47.8,49214.88,133012.713951,131848.002,0,7288.014352,50000,55000,24000,NaN,129000,42848.002,49000,NaN,65323.939111,49564,68517.000793,64233,6447.045743,6110,7288.014352,9673,147576.0,129580,NaN,NaN,NaN,NaN,NaN
6,2022-01-05,Wed,650,44.275547,28491.314519,577,44.6,25476.858,1100,49.94785,54393.208226,1105,48.2,52728.39,1000,49.94785,49448.371115,1043,48.2,49769.874,132332.89386,127975.122,0,8645.127518,45000,52000,28000,5300,130300,47975.122,53000,NaN,59060.496963,45890,59891.490569,61162,14752.88495,6061,8645.127518,9394,142350.0,122507,NaN,NaN,NaN,NaN,NaN

In [0]:
xls_fileT.columns.values

Out[8]: array([NaT, nan, 'Orders Fc', 'Basket Fc', 'Picking Fc', 'Orders Update',
       'Basket Update', 'Picking Update', 'Orders Fc', 'Basket Fc',
       'Picking Fc', 'Orders Update', 'Basket Update', 'Picking Update',
       'Orders Fc', 'Basket Fc', 'Picking Fc', 'Orders Update',
       'Basket Update', 'Picking Update', 'Total Picks Forecast',
       'Total Picks Update', 'Inbound Fc (no PO)', 'Pre-orders Fc',
       'Ochtend', 'Middag', 'Nacht', 'Delhome+Correctie', 'Leverdag',
       'Geschat', 'Actuals', nan, 'Dry Fc', 'Dry Actuals', 'Fresh Fc',
       'Fresh', 'Frozen Fc', 'Frozen', 'Ultrafresh Fc', 'Ultrafresh',
       'Total Inbound Fc', 'Total Inbound', 'Distrilog Dry',
       'Delhome Dry', 'Total Dry', 'Distrilog Rest', 'Total'],
      dtype=object)

In [0]:
import datetime as dt

In [0]:
xls_fileT1=xls_fileT.copy()

In [0]:
#using iloc, set the fist row to be the header and drop the row from the dataframe
#xls_fileT.rename(columns=xls_fileT.iloc[0]).drop(xls_fileT.index[0]).copy()

In [0]:
# xls_fileT.rename(columns=xls_fileT.iloc[0], inplace=True)
#xls_fileT = xls_fileT.rename(columns=xls_fileT.iloc[0]).copy()
# xls_fileT_NEW = xls_fileT.rename(columns=xls_fileT.iloc[0]).copy()
xls_fileT

,NaT,NaN,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Total Picks Forecast,Total Picks Update,Inbound Fc (no PO),Pre-orders Fc,Ochtend,Middag,Nacht,Delhome+Correctie,Leverdag,Geschat,Actuals,NaN,Dry Fc,Dry Actuals,Fresh Fc,Fresh,Frozen Fc,Frozen,Ultrafresh Fc,Ultrafresh,Total Inbound Fc,Total Inbound,Distrilog Dry,Delhome Dry,Total Dry,Distrilog Rest,Total
2,NaT,NaN,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Orders Fc,Basket Fc,Picking Fc,Orders Update,Basket Update,Picking Update,Total Picks Forecast,Total Picks Update,Inbound Fc (no PO),Pre-orders Fc,Ochtend,Middag,Nacht,Delhome+Correctie,Leverdag,Geschat,Actuals,NaN,Dry Fc,Dry Actuals,Fresh Fc,Fresh,Frozen Fc,Frozen,Ultrafresh Fc,Ultrafresh,Total Inbound Fc,Total Inbound,Distrilog Dry,Delhome Dry,Total Dry,Distrilog Rest,Total
3,NaT,NaN,4400.0,NaN,204840.741214,4323.0,NaN,200388.078,5580.0,NaN,288451.394266,5860.0,NaN,286562.331,5250.0,NaN,268811.635976,5572.0,NaN,273058.731,762103.771455,760009.14,0.0,44682.948876,NaN,NaN,NaN,NaN,796800.0,NaN,NaN,NaN,369906.91178,300694.072927,332313.282109,311828.441701,95928.857236,35021.899948,44682.948876,46876.802626,842832.0,694421.217201,NaN,NaN,NaN,NaN,NaN
4,2022-01-03,Mon,700,43.656843,30254.192107,615,44.3,26972.055,200,49.51237,9803.449231,201,53.3,10606.167,700,49.51237,34312.072307,701,53.3,36989.667,74369.713644,74567.889,0,6538.217201,35000,55000,33000,NaN,123000,35000,34000,NaN,85794.442754,84224,60969.286307,41000,49273.053738,5581,6538.217201,6538.217201,202575,137343.217201,NaN,NaN,NaN,NaN,NaN
5,2022-01-04,Tue,750,41.534592,30839.434588,676,43.5,29111.94,1100,49.145397,53519.336809,1131,47.8,53521.182,1000,49.145397,48653.942554,1040,47.8,49214.88,133012.713951,131848.002,0,7288.014352,50000,55000,24000,NaN,129000,42848.002,49000,NaN,65323.939111,49564,68517.000793,64233,6447.045743,6110,7288.014352,9673,147576.0,129580,NaN,NaN,NaN,NaN,NaN
6,2022-01-05,Wed,650,44.275547,28491.314519,577,44.6,25476.858,1100,49.94785,54393.208226,1105,48.2,52728.39,1000,49.94785,49448.371115,1043,48.2,49769.874,132332.89386,127975.122,0,8645.127518,45000,52000,28000,5300,130300,47975.122,53000,NaN,59060.496963,45890,59891.490569,61162,14752.88495,6061,8645.127518,9394,142350.0,122507,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,2022-12-28,Wed,950,41.52,39049.56,725,41,29427.75,1375,45.79,62331.6375,1260,45.7,57006.18,1250,45.79,56665.125,862,45.7,38999.466,158046.3225,125433.396,0,9509.601394,65000,62000,47000,NaN,174000,-14566.604,29000,NaN,71916.32,47680,62406.358606,57239,5883.382433,5253,9509.601394,10525,149715.662433,120697,NaN,NaN,NaN,NaN,NaN
415,2022-12-29,Thu,1400,40.8,56548.8,895,39.1,34644.555,1375,46.05,62685.5625,831,45.4,37350.126,1250,46.05,56986.875,1042,45.4,46833.732,176221.2375,118828.413,0,9399.318,65000,62000,53000,NaN,180000,-26171.587,23000,NaN,60346.346,39552,76619.568,63748,5951.031775,6037,9399.318,10458,152316.263775,119795,NaN,NaN,NaN,NaN,NaN
416,2022-12-30,Fri,1950,40.35,77895.675,1539,41.4,63077.454,1375,45.55,62004.9375,1311,46.2,59962.518,1250,45.55,56368.125,1072,46.2,49031.136,196268.7375,172071.108,0,9096.132,65000,62000,56000,NaN,183000,15071.108,36000,NaN,52203.888,61119,65006.548,42234,5759.074282,6692,9096.132,7824,132065.642282,117869,NaN,NaN,NaN,NaN,NaN
417,2022-12-31,Sat,1850,35.34,64725.21,1300,32.8,42213.6,1300,45.09,58030.83,1311,44.3,57496.527,0,45.09,0,0,45.09,0,122756.04,99710.127,0,7219.766,19000,NaN,NaN,NaN,19000,-47289.873,NaN,NaN,62750.131426,46818,60982.180799,44876,5269.921775,4932,7219.766,5975,136222.0,102601,NaN,NaN,NaN,NaN,NaN
418,2023-01-01,Sun,1850,35.34,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,45.09,NaN,0,45.09,NaN,0,0,0,7219.766,NaN,NaN,35000,NaN,35000,-66289.873,NaN,NaN,62750.131426,NaN,60982.180799,NaN,5269.921775,NaN,7219.766,NaN,136222.0,0,NaN,NaN,NaN,NaN,NaN

In [0]:
(xls_fileT1.set_index[0]).loc[4:,[ 'Frozen', 'Ultrafresh Fc',	'Ultrafresh']]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <command-1553242820424155>:1
----> 1 (xls_fileT1.set_index[0]).loc[4:,[ 'Frozen', 'Ultrafresh Fc',	'Ultrafresh']]

TypeError: 'method' object is not subscriptable

In [0]:
(xls_fileT.set_index(xls_fileT.iloc[:,0]))[[ 'Frozen', 'Ultrafresh Fc',	'Ultrafresh']]

In [0]:
(((xls_fileT1
   .set_index(xls_fileT1.iloc[:,0])) # Convert the date to an index --> solves the issue of not having a column name
  [['Dry Fc','Dry Actuals','Fresh Fc','Fresh','Frozen Fc','Frozen', 'Ultrafresh Fc',	'Ultrafresh']]) # --> select the columns of interest
 .iloc[1:,]) # select the indexes of interest (i.e., skip first row)

 ## Could we rename the date column from the beginning?
 ## Could we reset the index (drop it and convert to
  # column) and then set a name??

In [0]:
xls_fileT1.rename_axis("Dates")

## Next steps:

1. Remove rows with NA values
1. Refactor into multiple functions that take the desired xlsx and output the final dataframe (1 function = 1 task)

In [0]:
(((xls_fileT1
   .set_index(xls_fileT1.iloc[:,0])) # Convert the date to an index --> solves the issue of not having a column name
  [['Dry Fc','Dry Actuals','Fresh Fc','Fresh','Frozen Fc','Frozen', 'Ultrafresh Fc',	'Ultrafresh']]) # --> select the columns of interest
 .iloc[1:,])

In [0]:
xls_df

### New subdataframe xls_df

In [0]:
xls_df=xls_fileT1.loc[4:]
xls_df.head()

In [0]:
# rename the dates column
xls_df.rename(columns={xls_df.columns[0]: 'Dates'}).head()
# set it as index

In [0]:
# select Useful column
xls_df1=(((xls_df
   .set_index(xls_df.iloc[:,0])) # Convert the date to an index --> solves the issue of not having a column name
  [['Dry Fc','Dry Actuals','Fresh Fc','Fresh','Frozen Fc','Frozen', 'Ultrafresh Fc',	'Ultrafresh']]) # --> select the columns of interest
 .iloc[1:,])

In [0]:
any(xls_df1[i].hasnans for i in xls_df1)
# drop nan values on the level of the row
#

In [0]:
xls_df1

In [0]:
xls_df1=xls_df1.dropna()

In [0]:
xls_df1.columns.values

In [0]:
for col in xls_df1:
  xls_df1[col] = xls_df1[col].astype(float)
#xls_df1.dtypes

In [0]:
xls_df1.dtypes

In [0]:
xls_df1

In [0]:
xls_df1.describe()